version: "3"

services:
  app:
    image: repo-list-dev
    container_name: repo-list
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./public:/app/public
      - ./src:/app/src
      - ./node_modules:/app/node_modules
